spring.application.name=hospital


spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:doctor.sql

third_party.api = https://jsonplaceholder.typicode.com/posts


# logging configuration
logging.level.com.ermapsh.dto=trace
logging.pattern.console=%d{dd-mm-yyyy hh:MM:ss} [%level] %c{.1} ---%m%n

# log handler
logging.file.name = application.log
logging.config=classpath:logback-spring.xml

# actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author=ErMapsh
info.app.description=this is test
info.app.version=1.0.0

#security config
spring.security.user.name=user
spring.security.user.password=admin
spring.security.jwt.secret_key=thisismysecretkeyfornowthisismysecretkeyfornowthisismysecretkeyfornow

deploy.env = development


@Value("${JWT.CLIENT_ID}")
private String clientId;

@Value("${JWT.CLIENT_SECRET}")
private String clientSecret;

spring.security.oauth2.client.registration.google.client-id =clientId
spring.security.oauth2.client.registration.google.client-secret = clientSecret
